import type { Metadata } from "next";
import { Poppins, Outfit } from "next/font/google";
import "./styles/globals.scss";
import AuthForm from "./(auth)/authForm";
import Nav from "./(nav)/nav";
import Toast from "./(toast)/toast";
import GlobalModals from "./styles/globalModals";
import { auth } from "@/auth";

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const outfit = Outfit({
    subsets: ["latin"],
    variable: "--font-outfit",
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} ${outfit.variable}`}>
                <Nav />
                {children}
                <GlobalModals />
                <AuthForm />
                <Toast />
            </body>
        </html>
    );
}
